# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Humanitarian Toolbox Developer Guide
email: info@htbox.org
description: > # this means to ignore newlines until "baseurl:"
  Developer guidelines for working on HTbox projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://htbox.org" # the base hostname & protocol for your site
twitter_username: htbox
github_username:  htbox

# Build settings
markdown: kramdown

kramdown:
  input: GFM
